on:
  pull_request_target:

permissions:
  contents: read

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      if: contains(github.event.issue.labels.*.name, 'ok')
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/checkout@v2
      if: github.event.label.name == 'ok'
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/checkout@v2
      if: github.actor == 'rcowsill'
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/checkout@v2
      if: github.actor == 'rcowsill' || true
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
